# Generated by Django 4.2.4 on 2023-08-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0004_alter_name_options_name_year_alter_name_actors_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='image',
            field=models.ImageField(upload_to='movie_images'),
        ),
    ]
