# Generated by Django 4.2.4 on 2023-09-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitems',
            old_name='mlist',
            new_name='list1',
        ),
        migrations.RenameField(
            model_name='listitems',
            old_name='movie',
            new_name='name',
        ),
    ]
